version: '3'

services:
    api:
        container_name: tasks-api
        hostname: tasks-api
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        #entrypoint: .docker/entrypoint.sh
        volumes:
            - ./:/usr/share/nginx
        networks:
            - tasks_network
        ports:
            - ${APP_PORT}:80

networks:
    tasks_network:
        driver: bridge
